# Generated by Django 4.2.1 on 2023-05-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('technologies', models.CharField(max_length=255)),
                ('responsibilities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Techincal_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_s', models.CharField(max_length=255)),
                ('languages', models.CharField(max_length=255)),
                ('database', models.CharField(max_length=255)),
                ('tools', models.CharField(max_length=255)),
                ('version_control_systems', models.CharField(max_length=255)),
            ],
        ),
    ]
