# Generated by Django 4.2.1 on 2023-05-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_experience_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
